Imports Infragistics.Win
Imports Infragistics.Win.UltraWinGrid

Public Class frmProva
    Implements IDisposable

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

#Region "Metodes"

    Public Sub Entrada(Optional ByVal pID As Integer = 0)

        Try

            Me.AplicarDisseny()


            fieldNombre1.SortBySummaryInfo.Field = fieldNumHores1
            fieldNombre1.SortOrder = DevExpress.XtraPivotGrid.PivotSortOrder.Descending
            PivotGridControl1.OptionsView.ShowRowGrandTotals = False


        Catch ex As Exception
            Mensaje.Mostrar_Mensaje_Error(ex)
        End Try

    End Sub



#End Region

    Private Sub PivotGridControl1_CustomCellValue(sender As Object, e As DevExpress.XtraPivotGrid.PivotCellValueEventArgs) Handles PivotGridControl1.CustomCellValue
        If IsNothing(e.Value) = True Then
            e.Value = 0.0
        End If
    End Sub

    Private Sub UltraButton1_Click(sender As Object, e As EventArgs) Handles UltraButton1.Click
        Dim _App As New Microsoft.Office.Interop.Excel.Application
        Dim _WB As Microsoft.Office.Interop.Excel.Workbook = _App.Workbooks.Open("C:\Users\Marta\Desktop\Temp1.xlsx")
        Dim _WS As Microsoft.Office.Interop.Excel.Worksheet = _WB.Sheets.Item(1)

        Dim _NomReferencia As String = ""
        Dim _ContaFotos As Integer = 1

        For _Files As Integer = 2 To 3000
            _NomReferencia = _WS.Cells(_Files, 1).value()

            If _NomReferencia <> "" AndAlso _NomReferencia <> _WS.Cells(_Files - 1, 1).value() Then
                System.IO.File.Copy("C:\Temp1\image" & _ContaFotos & ".jpeg", "c:\Temp1\Transformada\" & _NomReferencia & ".jpeg")
                _ContaFotos = _ContaFotos + 1
            End If

        Next

        _WB.Save()
        _WB.Close()
        _App.Quit()
        _App = Nothing
        _WB = Nothing
        _WS = Nothing
    End Sub
End Class